
services:
  geonetwork:
    volumes:
      # client-specific customisations
      # osmp
      - ../iso19139.osmp/src/main/plugin/iso19139.osmp:/var/lib/jetty/webapps/geonetwork/WEB-INF/data/config/schema_plugins/iso19139.osmp
      - ../iso19139.osmp/src/main/config/translations/en-schema-iso19139.osmp.json:/var/lib/jetty/webapps/geonetwork/catalog/locales/en-schema-iso19139.osmp.json
      - ../iso19139.osmp/target/schema-iso19139.osmp-4.2.4-SNAPSHOT.jar:/var/lib/jetty/webapps/geonetwork/WEB-INF/lib/gn-schema-iso19139.osmp-4.2.4-SNAPSHOT.jar
      # persistent logo and favicon
      - ./ordnance-survey/OS-logo.png:/var/lib/jetty/webapps/geonetwork/WEB-INF/data/data/resources/images/logos/044fac9d-3bba-4214-b010-eeb9978422b2.png
      - ./ordnance-survey/OS-favicon.png:/var/lib/jetty/webapps/geonetwork/WEB-INF/data/data/resources/images/logos/favicon.png
      # strings overrides
      - ./ordnance-survey/catalog/locales/en-custom.json:/var/lib/jetty/webapps/geonetwork/catalog/locales/en-custom.json
      # string overrides TO CHECK
      #- ./ordnance-survey/catalog/locales/en-admin.json:/var/lib/jetty/webapps/geonetwork/catalog/locales/en-admin.json
      #- ./ordnance-survey/catalog/locales/en-core.json:/var/lib/jetty/webapps/geonetwork/catalog/locales/en-core.json
      #- ./ordnance-survey/catalog/locales/en-editor.json:/var/lib/jetty/webapps/geonetwork/catalog/locales/en-editor.json
      #- ./ordnance-survey/catalog/locales/en-gnui.json:/var/lib/jetty/webapps/geonetwork/catalog/locales/en-gnui.json
      #- ./ordnance-survey/catalog/locales/en-v4.json:/var/lib/jetty/webapps/geonetwork/catalog/locales/en-v4.json
      # gemini 2.3 overrides for NGD
      - ./geonetwork/WEB-INF/data/config/schema_plugins/iso19139.gemini23/layout/config-editor.xml:/var/lib/jetty/webapps/geonetwork/WEB-INF/data/config/schema_plugins/iso19139.gemini23/layout/config-editor.xml
      - ./geonetwork/WEB-INF/data/config/schema_plugins/iso19139.gemini23/index-fields/index-subtemplate.xsl:/var/lib/jetty/webapps/geonetwork/WEB-INF/data/config/schema_plugins/iso19139.gemini23/index-fields/index-subtemplate.xsl
