version: '2'

services:
  geonetwork:
    logging:
        driver: awslogs
        options: 
          awslogs-group: docker-geonetwork
          awslogs-region: eu-west-2
          awslogs-stream-prefix: geonetwork

  elasticsearch:
    logging:
          driver: awslogs
          options: 
            awslogs-group: docker-geonetwork
            awslogs-region: eu-west-2
            awslogs-stream-prefix: geonetwork

  kibana:
    environment:
      ELASTICSEARCH_URL: http://localhost:9200/
    logging:
          driver: awslogs
          options: 
            awslogs-group: docker-geonetwork
            awslogs-region: eu-west-2
            awslogs-stream-prefix: geonetwork
    volumes:
      - ../kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
      - ../kibana/dashboard/export.ndjson:/usr/share/kibana/dashboard/export.ndjson

  postgres:
    logging:
          driver: awslogs
          options: 
            awslogs-group: docker-geonetwork
            awslogs-region: eu-west-2
            awslogs-stream-prefix: geonetwork

  nginx:
    image: nginx
    volumes:
      - ../nginx/default:/etc/nginx/conf.d/default.conf
      - ../nginx/os-csw-api.inc:/etc/nginx/conf.d/os-csw-api.inc
    ports:
      - 80:80
    logging:
          driver: awslogs
          options: 
            awslogs-group: docker-geonetwork
            awslogs-region: eu-west-2
            awslogs-stream-prefix: nginx


