version: 1
task_definition:
  #task_execution_role: ecsTaskExecutionRole
  ecs_network_mode: awsvpc
  task_size:
    mem_limit: 7168
    cpu_limit: 1024
services:
  geonetwork:
    mem_limit: 2048   
    container_name: geonetwork
    healthcheck:
      test: ["CMD-SHELL", "curl -i -H \"Accept: application/json\" -f http://localhost:8080/geonetwork/srv/api/0.1/site || exit 1"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 5m
  elasticsearch:
    mem_limit: 2048
    container_name: elasticsearch
    healthcheck:
      test: ["CMD-SHELL", "curl -i -H \"Accept: application/json\" -f http://localhost:9200/gn-records || exit 1"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 5m
  kibana:
    mem_limit: 1024
    container_name: kibana
    healthcheck:
        test: ["CMD", "curl", "-s", "-f", "http://localhost:5601/login"]
        retries: 3
  nginx:
    container_name: nginx
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80/robots.txt || exit 1"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 5m


run_params:
  network_configuration:
    awsvpc_configuration:
      subnets:
        - "subnet-037e3e5e3c8cc9dd5" 
        - "subnet-0b64d89dcdc5f3549"
      security_groups:
        - "sg-079d1a2473d7cf600"

