version: 1
task_definition:
  task_execution_role: ecsTaskExecutionRole
  ecs_network_mode: awsvpc
  task_size:
    mem_limit: 6144
    cpu_limit: 1024
services:
  geonetwork:
    mem_limit: 2048
    container_name: geonetwork
    # depends_on:
    #   - container_name: database
    #     condition: "HEALTHY"
  elasticsearch:
    mem_limit: 2048
    container_name: elasticsearch
  kibana:
    mem_limit: 1024
    container_name: kibana
  postgres:
    mem_limit: 512
    container_name: postgres
    essential: false
    # healthcheck:
    #   test: ["CMD", "pg_isready -U geonetwork"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
  nginx:
    container_name: nginx


run_params:
  network_configuration:
    awsvpc_configuration:
      subnets:
        - "subnet-0e9130b270a4c4f11"
        - "subnet-0f253937562273b7f"
      security_groups:
        - "sg-039f0a97751903467"
docker_volumes:
  schemas:
    external: true

