version: 1
task_definition:
  task_execution_role: ecsTaskExecutionRole
  ecs_network_mode: awsvpc
  task_size:
    mem_limit: 7168
    cpu_limit: 1024
services:
  geonetwork:
    mem_limit: 2048   
    container_name: geonetwork
    healthcheck:
      test: ["CMD-SHELL", "curl -i -H \"Accept: application/json\" -f http://localhost:8080/geonetwork/srv/api/0.1/site || exit 1"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 5m
    # depends_on:
    #   - container_name: database
    #     condition: "HEALTHY"
  elasticsearch:
    mem_limit: 2048
    container_name: elasticsearch
  kibana:
    mem_limit: 1024
    container_name: kibana
  postgres:
    mem_limit: 512
    container_name: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U geonetwork"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 5m
  nginx:
    container_name: nginx
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80/robots.txt || exit 1"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 5m


run_params:
  network_configuration:
    awsvpc_configuration:
      subnets:
        - "subnet-0d89b9b6aadfadb2a"
        - "subnet-0d5ad36d370ef53f0"
      security_groups:
        - "sg-039f0a97751903467"

